# Funding platforms for nowo-tech/composer-update-helper
# These are supported funding model platforms

github: [HecFranco]
# patreon:
# open_collective:
# ko_fi:
# tidelift:
# community_bridge:
# liberapay:
# issuehunt:
# otechie:
# lfx_crowdfunding:
# custom:

